name=TinyPrinter
version=1.0.2
author=Ramiz Mammadli
maintainer=Ramiz Mammadli
sentence=Arduino library for X5H and compatible Bluetooth Thermal Printers (ESP32 / NimBLE).
paragraph=A feature-packed thermal printer library for X5H mini BLE printers. Supports custom fonts, multi-size built-in fonts (8x8, 5x7, 12x16, 16x24), Azerbaijani UTF-8 & Latin characters, custom alignment, bold/inverse/underline styles, thermal darkness controls, battery telemetry, and bitmap rendering.
category=Device Control
url=https://github.com/ramo828/tiny_print_library
architectures=esp32
includes=TinyPrinter.h
depends=NimBLE-Arduino
